export const ERROR = "ERROR";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const GET_REMINDERS = "GET_REMINDERS";
export const GET_REMINDERS_HAS_ERROR = "GET_REMINDERS_HAS_ERROR"